#
# Copyright (C) 2014 Broadcom Corporation
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation version 2.
#
# This program is distributed "as is" WITHOUT ANY WARRANTY of any
# kind, whether express or implied; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

obj-$(CONFIG_BCM_CYGNUS_PM) += iproc_pm.o iproc_pm_common.o
obj-$(CONFIG_BCM_CYGNUS_PM) += iproc_pm_suspend.o iproc_pm_sleep.o

